### ISSUE TITLE
Add the feature of Uploading file 

### ISSUE THREAD

**Issue by soumikbaithalu** [soumik2012/whatsapp-clone#10]
![image](https://user-images.githubusercontent.com/66599363/123732786-0e464380-d8b8-11eb-9c25-a715d60d5c18.png)

Add the function of the upload file so that the user can upload the file.

**Comment by anushruti11** [comment]
Can I work on this issue?

**Comment by soumikbaithalu** [comment]
@anushruti11 Yup you can, before I will assign the issue to you, can you tell me your approach here?

**Comment by shreya024** [comment]
@soumikbaithalu  I would like to work on this issue using material-ui-dropzone npm library.

**Comment by soumikbaithalu** [comment]
@shreya024 Go ahead I love to see your PR !! 👍🏻

**Comment by shreya024** [comment]
@soumikbaithalu I have added the file uploading ...it works. For now, all the uploaded files are console logged ...could you guide me how to send it to backend/db?

**Comment by soumikbaithalu** [comment]
@shreya024  If you can refer to this https://youtu.be/UxjVu4e8H2I this might be helpful if not then add the console logged feature

**Comment by shreya024** [comment]
> @shreya024 If you can refer to this https://youtu.be/UxjVu4e8H2I this might be helpful if not then add the console logged feature

Okay
