### ISSUE TITLE
Add copy to clipboard functionality in messages

### ISSUE THREAD

**Issue by soumikbaithalu** [soumik2012/whatsapp-clone#16]
Add a small icon on the message card. Clicking it will copy the contents of the message.

**Comment by eddierayo-156** [comment]
I would like to contribute to this issue

**Comment by soumikbaithalu** [comment]
@eddierayo-156  yes you can work on it.

**Comment by soumikbaithalu** [comment]
@eddierayo-156 can you tell me your approch here ?

**Comment by eddierayo-156** [comment]
Thank you for getting back to me. My approach will be to implement a button with a clipboard icon that will select the text box area. Once clicked, I think I'll implement a pop-up message stating that the text was copied successfully.

**Comment by soumikbaithalu** [comment]
That sound great go ahead !!

**Comment by Prathap-P** [comment]
@soumik2012 Since it is not assigned, I think I can take this issue. 
I'll add the icon at the chat footer and if it is clicked the content in the input element is copied to the clipboard. I think that can solve this.

**Comment by soumikbaithalu** [comment]
@Prathap-P Go ahead 👨‍💻
