### ISSUE TITLE
Position Scroll

### ISSUE THREAD

**Issue by Prathap-P** [soumik2012/whatsapp-clone#36]
It would be nice, if we can showing the latest message than showing the first message every time.

**Comment by Prathap-P** [comment]
I think it can be done by using useRef and referring the chat_body element. And using useEffect setting the ref's scroll position to point the whole scroll height.
Please assign me, I would like to work on this.

**Comment by soumikbaithalu** [comment]
@Prathap-P I didn't get ...you are saying if user typed some message instead of showjng the current msg you want to show first message...?

**Comment by Prathap-P** [comment]
@soumik2012  Ok, let me explain. After authentication when we opened any room, I thought it would be good, if we can set the chat body to scroll to the bottom of its height. So that one can always see the latest message in the room, than to scroll to the bottom always. The order of the messages are going to be same, the difference is when the body is mounted we should position the scroll to the bottom.

**Comment by soumikbaithalu** [comment]
Ohh..sound great @Prathap-P  go for it 😄 👍🏻
