### ISSUE TITLE
add some badges to the README

### ISSUE THREAD

**Issue by Umesh-01** [soumik2012/whatsapp-clone#39]
### **Is your feature request related to a problem? Please describe.**
Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help the users to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/125405621-8abb4500-e3d5-11eb-91d4-fe98c3fe4149.png)

### **Describe the solution you'd like**
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### **Work under/as**
- [x] LGMSOC
- [ ] Contributor

**Comment by soumikbaithalu** [comment]
@Umesh-01 Great Go For it
