### ISSUE TITLE
add Fav Icon to website 

### ISSUE THREAD

**Issue by soumikbaithalu** [soumik2012/whatsapp-clone#48]
**Is your feature request related to a problem? Please describe.**
Add a fav Icon to the website

**Comment by anuragc10** [comment]
I can work on this can you assign this issue to me.

**Comment by soumikbaithalu** [comment]
Yes you can @anuragc10 Take image from `readme.md` file and make it square okay

**Comment by anuragc10** [comment]
can you please specify what type of favicon you want? 
 1. name or without a name(chathub).
 2. with the same background or transparent.

**Comment by anuragc10** [comment]
I have added favicon #53 

![2](https://user-images.githubusercontent.com/63997049/128624752-afb324ab-5bfa-4643-a6c4-2ab2e559287a.PNG)
