### ISSUE TITLE
package.json missing lint script .

### ISSUE THREAD

**Issue by saurabhmehta1601** [soumik2012/whatsapp-clone#49]
# What is the issue ??
The steps to contribute to project in contributing.md include step ` npm run lint` but this script is missing in `package.json`

# How To Reproduce bug ??
1. Run `npm run lint` from your terminal in  the cloned  project  directory on your host machine . 

# Expected behavior
On running script `npm run lint` Eslint should lint files successfully without giving errors .

# Screenshot
![Screenshot from 2021-07-21 10-38-20](https://user-images.githubusercontent.com/57309205/126434634-c1a7e745-9f5a-482b-a695-8eec5f8a1878.png)

# Desktop Environment
 - OS: Ubuntu 20.04.2 LTS

**Comment by soumikbaithalu** [comment]
@saurabhmehta1601 are you LGM-SOC'21 Participant?

**Comment by saurabhmehta1601** [comment]
No , I'm someone who is new to open source . Sorry , I didn't know this is part of some private event . Can I participation ??

**Comment by soumikbaithalu** [comment]
> No , I'm someone who is new to open source . Sorry , I didn't know this is part of some private event . Can I participation ??

of course, you can @saurabhmehta1601 open source is for all.
