### ISSUE TITLE
SearchBar should be fully expand

### ISSUE THREAD

**Issue by ZaidKhan2002** [soumik2012/whatsapp-clone#66]
**Is your feature request related to a problem? Please describe.**
I tried chathub and in top search bar is only limited to certain space it is not looking good.

**Describe the solution you'd like**
It should be fully expand to total width of that particular container.

**Additional context**
<img width="570" alt="Screenshot 2021-12-19 at 8 16 22 PM" src="https://user-images.githubusercontent.com/71960989/146679634-ae5ed309-3c99-4f34-9981-5d44e464e23d.png">

**Comment by soumikbaithalu** [comment]
@ZaidKhan2002 Go Ahead 👍🏻

**Comment by ZaidKhan2002** [comment]
I am closing this issue as PR regarding this is already merged !!
